routes/admin.php
<?php

Route::group(['prefix'=>'admin', 'middleware' => ['auth','admin']], function () {

    Route::get('/', 'Admin\DashboardController@index')->name('admin');
    Route::resource('/berita','Admin\BeritaController');
    Route::resource('/kategori','Admin\KategoriController');
    Route::resource('/user','Admin\UserController');

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::group(['prefix'=>'apps', 'middleware' => ['auth','apps']], function () {

    Route::get('/', 'Apps\DashboardController@index')->name('apps');

});

app/Http/Controllers/Admin/KategoriController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Kategori;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    public function __construct()
    {
        $this->title = 'kategori';
    }

    public function index()
    {
        $data = Kategori::all();
        return view('admin.kategori.index', compact('data'));
    }
    public function create()
    {
        return view('admin.kategori.create');
    }

    public function store(Request $request)
    {
        $model = $request->all();
        $model['user_id'] = auth()->user()->id;
        $data = Kategori::create($model);
        if($data){
            Alert::toast('Data Berhasil Disimpan', 'success');
        }else{
            Alert::toast('Data Berhasil Disimpan', 'danger');
        }
        return redirect('admin/kategori');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Kategori::find($id);
        return view('admin.kategori.edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $model = $request->all();
        $data = Kategori::find($model['id']);
        $model['user_id'] = auth()->user()->id;
        if($data->update($model)){
            Alert::toast('Data Berhasil Diupdate', 'success');
        }else{
            Alert::toast('Data Berhasil Diupdate', 'danger');
        }
        return redirect('admin/kategori');
    }

    public function destroy(Request $request, $id)
    {
        $data = Kategori::find($id);
        if($data->delete()){
            Alert::toast('Data Berhasil Diupdate', 'success');
        }else{
            Alert::toast('Data Berhasil Diupdate', 'danger');
        }
        return redirect('admin/kategori');
    }
}

resources/views/admin/kategori/create.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Form Input Berita
    @endcomponent
@endpush

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Form</h3>
                </div>


                <form action="{{ route('kategori.store') }}" method="post">

                    @include('admin.kategori.form')

                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button class="btn btn-danger">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>

                </form>


            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

resources/views/admin/kategori/edit.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Form Input Berita
    @endcomponent
@endpush

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Form</h3>
                </div>

                <form action="{{ route('kategori.update', $data->id) }}" method="post">

                    <input name="_method" type="hidden" value="PATCH">
                    <input name="id" type="hidden" value="{{$data->id}}">


                @include('admin.kategori.form')

                <!-- /.card-body -->
                    <div class="card-footer">
                        <button class="btn btn-danger">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>

                </form>


            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

resources/views/admin/kategori/form.blade.php
@csrf
<!-- /.card-header -->
<div class="card-body">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Kategori</label>
                <input type="text" class="form-control" name="kategori" value="{{ isset($data->kategori) ? $data->kategori :
                null }}" required>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>

resources/views/admin/kategori/index.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Berita
    @endcomponent
@endpush

@section('content')

    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Data</h3>
                        <div class="float-right">
                            <a href="{{ route('kategori.create') }}"
                               class="btn btn-danger btn-xs">
                                <i class="fa fa-plus"></i> Create
                            </a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Kategori</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $no => $v)
                                <tr>
                                    <td> {{ ++$no }}</td>
                                    <td>{{ $v->kategori }}</td>
                                    <td>
                                        <form class="" method="POST"
                                              action="{{ route('kategori.destroy', $v->id) }}">
                                            {{ csrf_field() }}
                                            <input name="_method" type="hidden" value="DELETE">
                                            <a href="{{ route('kategori.edit',$v->id) }}"
                                               class="btn btn-primary btn-xs" title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <button type="submit"
                                                    class="btn btn-danger btn-xs js-submit-confirm"
                                                    title="Hapus"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection