routes/admin.php
<?php

Route::group(['prefix'=>'admin', 'middleware' => ['auth','admin']], function () {

    Route::get('/', 'Admin\DashboardController@index')->name('admin');
    Route::resource('/berita','Admin\BeritaController');
    Route::resource('/kategori','Admin\KategoriController');
    Route::resource('/user','Admin\UserController');

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


Route::group(['prefix'=>'apps', 'middleware' => ['auth','apps']], function () {

    Route::get('/', 'Apps\DashboardController@index')->name('apps');

});

app/Http/Controllers/Admin/BeritaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Berita;
use Alert;

class BeritaController extends Controller
{
    public function __construct()
    {
        $this->title = 'berita';
    }

    public function index()
    {
        $data = Berita::all();
        return view('admin.berita.index', compact('data'));
    }
    public function create()
    {
        return view('admin.berita.create');
    }
    public function store(Request $request)
    {
        $model = $request->all();
        $model['user_id'] = auth()->user()->id;
        $data = Berita::create($model);
        if($data){
            Alert::toast('Data Berhasil Disimpan', 'success');
        }else{
            Alert::toast('Data Berhasil Disimpan', 'danger');
        }
        return redirect('admin/berita');
    }
    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Berita::find($id);
        return view('admin.berita.edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $model = $request->all();
        $data = Berita::find($model['id']);
        $model['user_id'] = auth()->user()->id;
        if($data->update($model)){
            Alert::toast('Data Berhasil Diupdate', 'success');
        }else{
            Alert::toast('Data Berhasil Diupdate', 'danger');
        }
        return redirect('admin/berita');
    }

    public function destroy(Request $request, $id)
    {
        $data = Berita::find($id);
        if($data->delete()){
            Alert::toast('Data Berhasil Diupdate', 'success');
        }else{
            Alert::toast('Data Berhasil Diupdate', 'danger');
        }
        return redirect('admin/berita');
    }
}

resources/views/admin/berita/create.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Form Input Berita
    @endcomponent
@endpush

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Form</h3>
                </div>


                <form action="{{ route('berita.store') }}" method="post">

                    @include('admin.berita.form')

                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button class="btn btn-danger">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>

                </form>


            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

resources/views/admin/berita/edit.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Form Input Berita
    @endcomponent
@endpush

@section('content')

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Form</h3>
                </div>

                <form action="{{ route('berita.update', $data->id) }}" method="post">

                    <input name="_method" type="hidden" value="PATCH">
                    <input name="id" type="hidden" value="{{$data->id}}">


                @include('admin.berita.form')

                <!-- /.card-body -->
                    <div class="card-footer">
                        <button class="btn btn-danger">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>

                </form>


            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

resources/views/admin/berita/form.blade.php
@csrf
<!-- /.card-header -->
<div class="card-body">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Judul</label>
                <input type="text" class="form-control" name="judul" value="{{ isset($data->judul) ? $data->judul :
                null }}" required>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>Kategori</label>
                <select class="form-control select2" style="width: 100%;" name="kategori">
                    @foreach(\App\Model\Kategori::all() as $v)
                        <option>{{$v->kategori}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label>Deskripsi</label>
                <textarea type="text" class="form-control" name="deskripsi" >
                    {{ isset($data->deskripsi) ? $data->deskripsi : null }}
                                </textarea>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label>Isi</label>
                <textarea type="text" class="form-control" name="isi" >
                    {{ isset($data->isi) ? $data->isi : null }}
                                </textarea>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>

resources/views/admin/berita/index.blade.php
@extends('admin.index')

@push('head-tabel')
    @component('_card.head')
        Berita
    @endcomponent
@endpush

@section('content')

    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Data</h3>
                        <div class="float-right">
                            <a href="{{ route('berita.create') }}"
                               class="btn btn-danger btn-xs">
                                <i class="fa fa-plus"></i> Create
                            </a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Judul</th>
                                <th>Kategori</th>
                                <th>user</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $no => $v)
                                <tr>
                                    <td> {{ ++$no }}</td>
                                    <td>{{ $v->judul }}</td>
                                    <td>{{ $v->kategori }}</td>
                                    <td>{{ $v->user_id }}</td>
                                    <td>
                                        <form class="" method="POST"
                                              action="{{ route('berita.destroy', $v->id) }}">
                                            {{ csrf_field() }}
                                            <input name="_method" type="hidden" value="DELETE">
                                            <a href="{{ route('berita.edit',$v->id) }}"
                                               class="btn btn-primary btn-xs" title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <button type="submit"
                                                    class="btn btn-danger btn-xs js-submit-confirm"
                                                    title="Hapus"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection